@baseURL= http://localhost:8080

###
Get {{baseURL}}/api/v1/products?limit=10&&offset=0

###
GET {{baseURL}}/api/v1/products/1234567891021

###
Get {{baseURL}}/api/v1/products/buy/logs?limit=15

###
Get {{baseURL}}/api/v1/products/arrive/logs?limit=10

###
POST {{baseURL}}/api/v1/products HTTP/1.1
Content-Type: application/json

{
    "name":"じゃがりこ関西だし味",
    "barcode":123456788,
    "price":220,
    "tag_id":1
}

###
POST {{baseURL}}/api/v1/products/buy
Content-Type: application/json

{
    "pay_at": "2024-02-05T23:32:37.115934+09:00",
    "method": "cash",
    "user_number": "K20079",
    "products": [
        {
            "id": 2,
            "quantity": 1,
            "unit_price":120
        },
        {
            "id": 3,
            "quantity": 3,
            "unit_price":120
        }
    ]
}

###
POST {{baseURL}}/api/v1/products/arrive
Content-Type: application/json

{
    "arrive_at": "2024-02-06T23:32:37.115934+09:00",
    "money": 2010,
    "products": [
        {
            "id": 2,
            "quantity": 10
        },
        {
            "id": 3,
            "quantity": 3
        }
    ]
}

###
PUT {{baseURL}}/api/v1/products
Content-Type: application/json

{
    "id":11,
    "name": "じゃがりこちーーず味",
    "barcode":1234567891021,
    "price":130,
    "stock":11,
    "tag_id":2
}

###
DELETE {{baseURL}}/api/v1/products/buy/21

###
DELETE {{baseURL}}/api/v1/products/arrival/12

###
GET {{baseURL}}/api/v1/assets

###
PUT {{baseURL}}/api/v1/assets
Content-Type: application/json

{
    "money":29292,
    "debt": 100
}

# カンマの有無でエラー:invalid character '}' looking for beginning of object key stringがでるため注意